version: '3'

services:
    mysql:
        container_name: mtmr_mysql
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: owner
            MYSQL_ROOT_PASSWORD: mtmr-data  # テキトーなパスワード
            MYSQL_PASSWORD: mtmr-data       # テキトーなパスワード
            MYSQL_DATABASE: mtmr-bot
        volumes:
            - ./db-data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
            - ./mysql/init/:/docker-entrypoint-initdb.d

    api:
        build: ./bot-api
        ports:
            - 8888:8888
        volumes:
            - ./bot-api:/go/src/bot-api
        depends_on:
            - 'mysql'

    application:
        build: ./projects
        ports:
            - 8080:8080
        volumes:
            - ./projects:/projects
        tty: true
